id: I64A0B8DA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-03-30T12:32:49+00:00'
last_modified: '2022-06-13T12:40:09.533984+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN21836
  title: ལོ་པན་གྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '1176':
      image_group_id: I3CN21897
      title: ''
      total_pages: ''
      order: 1
      base_file: 1176.txt
    FF34:
      image_group_id: I3CN21898
      title: ''
      total_pages: ''
      order: 2
      base_file: FF34.txt
    CF6D:
      image_group_id: I3CN21899
      title: ''
      total_pages: ''
      order: 3
      base_file: CF6D.txt
    '5626':
      image_group_id: I3CN21900
      title: ''
      total_pages: ''
      order: 4
      base_file: 5626.txt
    106E:
      image_group_id: I3CN21901
      title: ''
      total_pages: ''
      order: 5
      base_file: 106E.txt
    9F97:
      image_group_id: I3CN21902
      title: ''
      total_pages: ''
      order: 6
      base_file: 9F97.txt
    '9340':
      image_group_id: I3CN21903
      title: ''
      total_pages: ''
      order: 7
      base_file: 9340.txt
    '9947':
      image_group_id: I3CN21904
      title: ''
      total_pages: ''
      order: 8
      base_file: 9947.txt
    FF87:
      image_group_id: I3CN21905
      title: ''
      total_pages: ''
      order: 9
      base_file: FF87.txt
    '1928':
      image_group_id: I3CN21906
      title: ''
      total_pages: ''
      order: 10
      base_file: 1928.txt
    1E0E:
      image_group_id: I3CN21907
      title: ''
      total_pages: ''
      order: 11
      base_file: 1E0E.txt
    EC85:
      image_group_id: I3CN21908
      title: ''
      total_pages: ''
      order: 12
      base_file: EC85.txt
    260F:
      image_group_id: I3CN21909
      title: ''
      total_pages: ''
      order: 13
      base_file: 260F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
